[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.118.2",
    "python-multipart>=0.0.20",
    "qiskit>=2.2.1",
    "qiskit-ibm-runtime>=0.42.0",
    "uvicorn[standard]>=0.37.0",
    "websockets>=15.0.1",
]
